name: Frontend CI Trigger QA

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  trigger-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger QA Automation on Staging
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.QA_TRIGGER_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/SumonMohammad/nifty-playwrigt-automation/dispatches \
            -d '{
              "event_type": "run-staging-tests",
              "client_payload": {
                "source": "frontend-repo",
                "commit": "${{ github.sha }}"
              }
            }'
